# Generated by Django 5.1.5 on 2025-03-16 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='alternative_contact',
            new_name='secondary_contact',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='alternative_contact',
            new_name='secondary_contact',
        ),
    ]
