# Generated by Django 5.1.5 on 2025-03-11 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionplans', '0003_remove_cashcollectionscheme_created_by_and_more'),
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='collectionplans.scheme'),
        ),
    ]
