# Generated by Django 5.1.5 on 2025-03-11 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectionplans', '0003_remove_cashcollectionscheme_created_by_and_more'),
        ('financials', '0002_alter_transaction_scheme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashCollectionScheme',
        ),
    ]
